---
# cfssl and cfssljson binaries are required to generate certs. Download them from the cfssl repository.
# https://pkg.cfssl.org/
# This tasks will be performed on client machine

- name: Install cfssl and cfssljson binaries
  get_url:
    url: "{{item}}"
    dest: /usr/local/bin/
    mode: 0755
  with_items:
    - "{{cfssl_linux}}"
    - "{{cfssljson_linux}}"

- name: Rename copied files
  copy:
    remote_src: True
    src: /usr/local/bin/{{item.srcfile}}
    dest: /usr/local/bin/{{item.destfile}}
    mode: 0755
  with_items:
    - { srcfile: cfssl_linux-amd64, destfile: cfssl}
    - { srcfile: cfssljson_linux-amd64, destfile: cfssljson}
  ignore_errors: false

- name: Delete old files
  file:
    path: /usr/local/bin/{{item}}
    state: absent
  with_items:
    - cfssl_linux-amd64
    - cfssljson_linux-amd64

- name: Verify cfssl version 1.2.0 or higher is installed
  shell: /usr/local/bin/cfssl version
  register: cfssl_version
- debug:
    msg: "{{cfssl_version.stdout_lines}}"
