---
- name: Check if kubectl package is already Installed
  stat:
    path: /usr/local/bin/kubectl
  register: kubectl_file

- name: Download and Install kubectl
  get_url:
    url: "{{kubectl_pkg}}"
    dest: /usr/local/bin/
    mode: 0755
  when: kubectl_file.stat.path is not defined

- name: Set ownership of kubectl binary
  file:
    path: /usr/local/bin/kubectl
    owner: "{{ansible_ssh_user}}"
    mode: 0755

- name: Verify kubectl version 1.7.4 or higher is installed
  shell: /usr/local/bin/kubectl version --client
  register: kubectl_version
- debug:
    var: kubectl_version.stdout
