---
# The Kubelet Client Certificates

# Kubernetes uses a special-purpose authorization mode called Node Authorizer, that specifically authorizes API requests made by Kubelets.
# In order to be authorized by the Node Authorizer, Kubelets must use a credential that identifies them as being in the system:nodes group,
# with a username of system:node:<nodeName>. 
# In this section you will create a certificate for each Kubernetes worker node that meets the Node Authorizer requirements.

# Generate a certificate and private key for each Kubernetes worker node:

- name: Create csr.json for each worker machine using create-worker-csr-json.sh
  script: /k8s/certs/create-worker-csr-json.sh {{ hostvars[item].ansible_host }}
  with_items: "{{ groups['nodes'] }}"
  ignore_errors: false
