---
# The Kubelet Client Certificates

# Kubernetes uses a special-purpose authorization mode called Node Authorizer, that specifically authorizes API requests made by Kubelets.
# In order to be authorized by the Node Authorizer, Kubelets must use a credential that identifies them as being in the system:nodes group,
# with a username of system:node:<nodeName>. 
# In this section you will create a certificate for each Kubernetes worker node that meets the Node Authorizer requirements.

# Generate a certificate and private key for each Kubernetes worker node:

- name: Create csr.json for each worker machine using create-worker-csr-json.sh
  script: generate-worker-csr-json.sh {{ hostvars[item].ansible_host }}
  with_items: "{{ groups['nodes'] }}"
  ignore_errors: false
  
- name: Verify worker csr files are generated
  stat:
    path: /k8s/certs/{{hostvars[item].ansible_host}}-csr.json
  register: worker_csr_json
  with_items: "{{ groups['nodes'] }}"
  
#- name: Print the output to the console.
#  debug: var=worker_csr_json
  
- debug: var={{item.stat.path}}
  with_items: "{{ worker_csr_json.results }}"
  
# might as well try with echo too
- shell: echo {{ item.stat.path }}
  with_items: "{{ worker_csr_json.results }}"
  
#- fail:
#    msg: "[ ERROR ] Worker nodes csr files are failed to be created."
#  with_items: "{{ worker_csr_json.results }}"  
#  when: "{{ item.stat.path }}" is not defined
#  ignore_errors: false 
