---
# The kube-proxy Client Certificate
# Create the kube-proxy client certificate signing request:
#
- name: Copy kube-proxy client certificate signing request
  copy:
    src: kube-proxy-csr.json
    dest: /k8s/certs/
  ignore_errors: false

- name: Generate the kube-proxy client certificate and private key using generate-kube-proxy-client-cert.sh
  script: generate-kube-proxy-client-cert.sh
  ignore_errors: false

- name: Check if kube-proxy.pem file is created
  stat:
    path: /k8s/certs/kube-proxy.pem
  register: kube_proxy
  ignore_errors: false

- fail:
    msg: "[ ERROR ]  kube-proxy.pem file is failed to be created."
  when: kube_proxy.stat.path is not defined
  ignore_errors: false
  
- name: Check if kube-proxy-key.pem file is created
  stat:
    path: /k8s/certs/kube-proxy-key.pem
  register: kube_proxy_key
  ignore_errors: false

- fail:
    msg: "[ ERROR ] kube-proxy-key.pem file is failed to be created."
  when: kube_proxy_key.stat.path is not defined
  ignore_errors: false
