---
# The Kubernetes API Server Certificate
# The Kubernetes public IP address will be included in the list of subject alternative names for the Kubernetes server certificate.
# This will ensure the TLS certificate is valid for remote client access

- name: Copy k8s api certificate signing request
  copy:
    src: kubernetes-csr.json
    dest: /k8s/certs/
    backup: no
  ignore_errors: false

- name: Copy generate-k8s-api-server-cert.j2 script template to client machine
  template:
    src: 7-generate-k8s-api-server-cert.j2
    dest: /k8s/certs/generate-k8s-api-server-cert.sh
    mode: 0755
  ignore_errors: false

- name: Generate the Kubernetes certificate and private key
  shell: sh /k8s/certs/generate-k8s-api-server-cert.sh
  ignore_errors: false

- name: Check if kubernetes.pem file is created
  stat:
    path: /k8s/certs/kubernetes.pem
  register: k8s_api_cert
  ignore_errors: false

- debug:
    msg: "[ Information ] kubernetes.pem file is created."
  when: k8s_api_cert.stat.path is defined
  ignore_errors: false

- fail:
    msg: "[ ERROR ] kubernetes.pem file is failed to be created."
  when: k8s_api_cert.stat.path is not defined
  ignore_errors: false

- name: Check if kubernetes-key.pem file is created
  stat:
    path: /k8s/certs/kubernetes-key.pem
  register: k8s_api_cert_key
  ignore_errors: false

- debug:
    msg: "[ Information ] kubernetes-key.pem file is created."
  when: k8s_api_cert_key.stat.path is defined
  ignore_errors: false

- fail:
    msg: "[ ERROR ] kubernetes-key.pem file is failed to be created."
  when: k8s_api_cert_key.stat.path is not defined
  ignore_errors: false

- name: Delete script generate-k8s-api-server-cert.sh
  file:
    path: /k8s/certs/generate-k8s-api-server-cert.sh
    state: absent
